export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_UPDATED = "USER_UPDATED";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const WEB3_INITIALIZED = "WEB3_INITIALIZED";

export const ELECTION_RESULTS_RETRIEVED = "ELECTION_RESULTS_RETRIEVED";
export const GET_OPEN_ELECTIONS = "GET_OPEN_ELECTIONS";
export const CREATE_NEW_OPEN_ELECTION = "CREATE_NEW_OPEN_ELECTION";

export const INIT_CONTRACT_FACTORY_CONTRACT = "INIT_CONTRACT_FACTORY_CONTRACT";
export const INIT_OPEN_ELECTION_CONTRACT = "INIT_OPEN_ELECTION_CONTRACT";