//let abi = /* abi as generated by the compiler */;
let CrowdFunding = web3.eth.contract(abi);
let crowdfunding = CrowdFunding .at("*address*");

let event = ContractFactory.LogContractCreated({_from:web3.eth.coinbase},{fromBlock: 0, toBlock: 'latest'});

event.watch(function(error, result){
    if (!error)
    console.log(result);
});

//event.stopWatching();
